--JOINS:-
------------
--1.CROSS JOIN:-
--------------

SELECT
    *
FROM
    HR.EMPLOYEES;


SELECT
    *
FROM
    HR.DEPARTMENTS;


    --cross join

SELECT E.FIRST_NAME,E.EMAIL,E.JOB_ID,E.DEPARTMENT_ID,D.DEPARTMENT_NAME
FROM HR.EMPLOYEES E 
CROSS JOIN HR.DEPARTMENTS D;

--inner join

SELECT e.FIRST_NAME, e.EMAIL, e.JOB_ID, e.DEPARTMENT_ID, d.DEPARTMENT_NAME
FROM HR.EMPLOYEES e
INNER JOIN HR.DEPARTMENTS d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;

--left join

SELECT e.EMPLOYEE_ID, e.FIRST_NAME, d.DEPARTMENT_NAME
FROM HR.EMPLOYEES e
LEFT JOIN HR.DEPARTMENTS d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;

--right join

SELECT e.EMPLOYEE_ID, e.FIRST_NAME, d.DEPARTMENT_NAME
FROM HR.EMPLOYEES e
RIGHT JOIN HR.DEPARTMENTS d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;



--full outer join

SELECT e.EMPLOYEE_ID, e.FIRST_NAME, d.DEPARTMENT_NAME
FROM HR.EMPLOYEES e
FULL JOIN HR.DEPARTMENTS d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;

